version: '3.8'
services:
  cqr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r2ccp_jupyter
    runtime: nvidia
    command: >
      /bin/bash -c "
        jupyter lab --ip='*' --port=8888 --NotebookApp.token='AAAA' --NotebookApp.password='' --no-browser --allow-root
      "
    volumes:
      - ./:/tf/notebook
    ports:
      - "8888:8888"